# NDK_TOOLCHAIN_VERSION=4.4.3
# APP_PROJECT_PATH := $(shell pwd)
APP_BUILD_SCRIPT := $(APP_PROJECT_PATH)/Android.mk
APP_PROJECT_PATH := c:\openssl-1.0.1u
APP_STL := gnustl_static
#APP_CPPFLAGS := -frtti -fexceptions
APP_OPTIM := release
#APP_OPTIM := debug
APP_ABI := armeabi-v7a arm64-v8a
APP_PLATFORM := android-15
NDK_TOOLCHAIN_VERSION := 4.9
