/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_warningsys_jni_HelloWorld
#define _Included_com_warningsys_jni_HelloWorld
#ifdef __cplusplus
extern "C" 
{
#endif


JNIEXPORT int JNICALL Java_com_warningenc_nativecaller_NativeCaller_InitEnc(JNIEnv *, jobject,jint width,jint height);
JNIEXPORT int JNICALL Java_com_warningenc_nativecaller_NativeCaller_DeiniEnc(JNIEnv *, jobject);
JNIEXPORT int JNICALL Java_com_warningenc_nativecaller_NativeCaller_InputData(JNIEnv *, jobject, jint type, jbyteArray data, jint len);


#ifdef __cplusplus
}
#endif

#endif


